# Generated by Django 5.2.7 on 2025-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pnr_codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
