# Generated by Django 5.2.7 on 2025-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_pnr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_needed',
            field=models.BooleanField(default=False),
        ),
    ]
