# Generated by Django 5.2.7 on 2025-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_original_fare_booking_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refunded_seats',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
